export const TEXT = {

    topInfo1: "우리가 바라온 새로운 기부플랫폼, ",
    topInfo2: "M",
    topInfo3: "ATCH",
    middleInfo1: "사업자 등록번호 : 169-87-03025 | 대표 : 한승기",
    middleInfo2: "통신판매업 신고번호 : 2014-서울강남-03377",
    middleInfo3: "주소 : 인천시 연수구 송도미래로 30, E동 802호 ",
    middleInfo4: "고객센터 : 070-7954-4123",
    middleInfo5: "법인명 : 주식회사 매치컴퍼니",
    bottomInfo1: "서비스 이용약관",
    bottomInfo2: "개인정보처리방침",
    bottomInfo3: "사업자정보",
    signUpEmail: "이메일 (아이디)",
    signUpPassword: "비밀번호",
    signUpName: "이름",
    signUpPhoneNum: "연락처",
    signUpSex: "성별",
    signUpBirth: "출생연도",
    chkBox1: "[필수] 만 14세 이상입니다.",
    chkBox2: "[필수] MATCH 이용약관 및 개인정보 수집 및 이용에 동의",
    chkBox3: "[선택] 마케팅 목적의 개인정보 수집 및 이용 동의",
    chkBox4: "[선택] 광고성 정보 수신 동의",
    loginFormText1: "회원가입",
    loginFormText2: "아이디 찾기",
    loginFormText3: "비밀번호 찾기",
    loginFormInfo: "SNS 계정으로 간편 로그인",
    login: "로그인",

    lookaroundHeader: "기부 프로젝트",
    detailHeader: "후원처 소개",
    detailFooter: "*1,000원도 전달해드려요.",

    //결제 화면
    payTitle: "매치를 켜기",
    payTitle2: "기부금 결제하기",
    //결제1
    pay1Container1: "1. 후원자 정보",
    //결제 2
    pay2Container1: "2. 후원 신청",
    pay2Container2: "후원 프로젝트",
    pay2Container3: "M",
    pay2Container4: "ATCH with : ",
    //결제3
    pay3Container1: "3. 결제 수단을 선택해주세요.",
    pay3Container2: "정기 후원일",
    pay3Container3: "후원 금액",
    pay3Container4: "기부 수단",
    pay3Select1: "신용 / 체크카드 결제",
    pay3Select2: "계좌 등록 결제",
    pay3Alert: "안내사항",
    pay3Alert1: "* 첫 후원금은 즉시 결제되며,\n  다음달부터는 매월 선택한 결제일에 결제됩니다.\n* 출금일에 후원금이 승인되지 않으면, 재요청할 수 있습니다.",
    pay3Agree: "결제 내용에 모두 동의합니다.",
    pay3AgreeCK1: "결제대행 서비스 이용약관 동의",
    pay3AgreeCK2: "개인정보 제3자 정보 제공 동의",
    pay3AgreeLook: "보기",
    //결제카드
    cardName1: "비씨카드",
    cardName2: "국민카드",
    cardName4: "삼성카드",
    cardName6: "신한카드",
    cardName7: "현대카드",
    cardName8: "롯데카드",
    cardName11: "씨티카드",
    cardName12: "농협카드",
    cardName13: "수협카드",
    cardName14: "신협카드",
    cardName16: "우리카드",
    cardName15: "하나카드",
    cardName32: "우체국카드",
    cardName37: "카카오뱅크",
    cardName38: "K뱅크카드",
    cardNameEtc: "기타카드",
    //결제 카드 등록
    payRegisterTitile: "카드 정보 입력",
    payRegisterInfo: "(최초 1회 등록)",
    payRegisterCardNo: "카드번호",
    payRegisterCardNoInfo: "NNNN",
    payRegisterCardDate: "유효 기간 DATE",
    payRegisterPerson: "개인",
    payRegusterOffice: "사업자",
    payRegisterCardDateInfo: "MM / YY",
    payRegisterCardCVC: "CVC (카드 뒷면 숫자 3자리)",
    payRegisterCardCVCInfo: "NNN",
    payRegisterCardPW: "카드 비밀번호 앞 2자리",
    payRegisterCardPWInfo: "NN **",
    payRegisterBirth: "생년월일",
    payRegisterBirthInfo1: "생년월일 6자리",
    payRegisterBirthInfo2: "사업자 번호 10자리",


    //메뉴
    menu1: "성냥이와 기부하기",
    menu2: "기부금 창고 보러가기",
    menu2_1: "유기동물을 위한",
    menu2_DOG: "유기동물을 위한",
    menu2_2: "아이들을 위한",
    menu2_CHILD: "아이들을 위한",
    menu2_3: "바다를 위한",
    menu2_OCEAN: "바다를 위한",
    menu2_4: "시각장애인을 위한",
    menu2_VISUALLY_IMPAIRED: "시각장애인을 위한",
    menu3: "매치소개",

} as const;
