
export const TEXT = {

    topInfo1: "우리가 바라온 새로운 기부플랫폼, ",
    topInfo2: "M",
    topInfo3: "ATCH",
    middleInfo1: "사업자 등록번호 : 373-10-02623 | 대표 : 한승기",
    middleInfo2: "통신판매업 신고번호 : 2014-서울강남-03377",
    middleInfo3: "주소 : 부천시 부흥로 339, 301-B1 113-4(중동 스타펠리움) ",
    middleInfo4: "고객센터 : 070-7954-4123",
    bottomInfo1: "서비스 이용약관",
    bottomInfo2: "개인정보처리방침",
    bottomInfo3: "사업자정보",
    signUpEmail: "이메일 (아이디)",
    signUpPassword: "비밀번호",
    signUpName: "이름",
    signUpPhoneNum: "연락처",
    signUpSex: "성별",
    signUpBirth: "출생연도",
    chkBox1: "[필수] 만 14세 이상입니다.",
    chkBox2: "[필수] MATCH 이용약관 및 개인정보 수집 및 이용에 동의",
    chkBox3: "[선택] 마케팅 목적의 개인정보 수집 및 이용 동의",
    chkBox4: "[선택] 광고성 정보 수신 동의",
    loginFormText1: "회원가입",
    loginFormText2: "아이디 찾기",
    loginFormText3: "비밀번호 찾기",
    loginFormInfo: "SNS 계정으로 간편 로그인",
    login: "로그인",

    lookaroundHeader: "기부 프로젝트",
    detailHeader: "후원처 소개",
    detailFooter: "*1,000원도 전달해드려요.",
} as const;
